<a href="https://colab.research.google.com/github/pawarashwajeet/pawarashwajeet/blob/main/Array_shape_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Changing the Shape of an Array




In [1]:
import numpy as np
a = np.array(((1,2), (3,4)))
print(a)

[[1 2]
 [3 4]]


## flatten and ravel
+ To `flatten` a multidimensional array onto a sigle axis, numpy provides two methods to this:
  * **flatten** and
  * **ravel**

In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = a.flatten()


In [4]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
b[3] = 0

In [6]:
b

array([1, 2, 3, 0, 5, 6, 7, 8, 9])

In [7]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
c = a.ravel()

In [9]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
c[3] = 0

In [11]:
c

array([1, 2, 3, 0, 5, 6, 7, 8, 9])

Assignment to `b` didnt change a because they are completely independent objects that do not share their data. In contrast, the flattened array created by  taking a view on `a` with ravel refers to the same underlying data.

## Resize and Reshape
An array may be resized (in place) to a compatible shape, that is a shape with the same total number of elements with the resize method, which takes the new dimensions as its arguments.

In [12]:
a = np.linspace(1,4,4)

In [13]:
a

array([1., 2., 3., 4.])

In [14]:
a.resize(2,2)

In [15]:
a

array([[1., 2.],
       [3., 4.]])

In [16]:
   a = np.linspace(1,4,4)

In [17]:
a

array([1., 2., 3., 4.])

In [18]:
b = a.reshape(2,2)

In [19]:
b

array([[1., 2.],
       [3., 4.]])

In [20]:
b[0,0] = -99

In [21]:
b

array([[-99.,   2.],
       [  3.,   4.]])

In [23]:
a

array([-99.,   2.,   3.,   4.])

## Transposing an Array
The method transpose returns a view of an array with the axes transposed. For a 2-D array, this is the usual matrix transpose:

In [24]:
a = np.linspace(1,6,6).reshape(2,3)

In [25]:
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [26]:
a.transpose() # or simply a.T

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [27]:
b = np.array([100, 101, 102, 103])

In [28]:
b.transpose()

array([100, 101, 102, 103])

## Merging and Splitting Arrays
A clutch of NumPy methods merge and split arrays in different ways; **np.vstack, np.hstack** and **np.dstack** stack arrays vertically, horizontally an depthwise. For example

In [29]:
a = np.array([0,0,0,0])

In [30]:
b = np.array([1,1,1,1])

In [31]:
c = np.array([2,2,2,2])

In [32]:
np.vstack((a,b,c))

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])

In [33]:
np.dstack((a,b,c))

array([[[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [34]:
np.hstack((a,b,c))

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2])

The inverse operation, that is splitting of an array is done by **np.vsplit**, **np.hsplit** and **np.dsplit**

In [35]:
a = np.linspace(1,6,6)

In [36]:
a

array([1., 2., 3., 4., 5., 6.])

In [37]:
np.split(a,3)

[array([1., 2.]), array([3., 4.]), array([5., 6.])]

In [38]:
a = np.linspace(1,6,6)

In [39]:
a

array([1., 2., 3., 4., 5., 6.])

In [40]:
np.hsplit(a,(2,3,5))

[array([1., 2.]), array([3.]), array([4., 5.]), array([6.])]

In [41]:
a = np.ones((3,3))

In [42]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
np.vstack((a,np.array((2,2,2))))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [2., 2., 2.]])

In [47]:
a = np.ones((3,3))

In [48]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [51]:
np.hstack((a,np.array((2,2,2))))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [52]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [55]:
b = np.array((2,2,2))

In [56]:
b

array([2, 2, 2])

In [57]:
b = np.array((2,2,2)).reshape(3,1)

In [58]:
b

array([[2],
       [2],
       [2]])

In [59]:
np.hstack((a,b))

array([[1., 1., 1., 2.],
       [1., 1., 1., 2.],
       [1., 1., 1., 2.]])