<a href="https://colab.research.google.com/github/pawarashwajeet/pawarashwajeet/blob/main/Numpy_array_egs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = np.array((10,11,12,13))
a

array([10, 11, 12, 13])

In [11]:
import numpy as np
b = np.array([[10,11],[12,13]])
b
b[0,1]
b[1,1]
b[1,1] = 12.5
b
np.array([-1, 0, 2.1])

array([-1. ,  0. ,  2.1])

In [12]:
np.array([-1, 0.5, 2, -5], dtype=complex)

array([-1. +0.j,  0.5+0.j,  2. +0.j, -5. +0.j])

Random Junk array created using np.empty()

In [13]:
np.empty((3,4))

array([[3.86020186e-315, 0.00000000e+000, 2.10077583e-312,
        6.79038654e-313],
       [2.22809558e-312, 2.14321575e-312, 2.35541533e-312,
        6.79038654e-313],
       [2.22809558e-312, 2.14321575e-312, 2.46151512e-312,
        2.41907520e-312]])

In [17]:
np.ones((3,3),dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.arange(0, 5, 1)

array([0, 1, 2, 3, 4])

using retstep = true


In [21]:
x, dx = np.linspace(0, 2*np.pi, 100, retstep = True)
dx
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

using endpoint=False

In [23]:
x = np.linspace(0,10,5, endpoint=False)
x

array([0., 2., 4., 6., 8.])

Initializing an array from function

In [26]:
def f(x,y):
  return x**2 + 2*x*y + y**2
np.fromfunction(f,(3,4))

array([[ 0.,  1.,  4.,  9.],
       [ 1.,  4.,  9., 16.],
       [ 4.,  9., 16., 25.]])